name: 'lint'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

#      - name: Create aab
#        run: gradle assemble
      - name: gradle lint
        run : |
          gradle lint

      - name: Run check
        uses: roncsak/check@dev
